---
title: "PSYXXX: Moral Psychology (CRN: XXXXX)"
subtitle: "Department of Psychology, University of Oregon"
author: "Term, meeting days and times, location of course"
output:
  html_document:
    theme: flatly
    toc: yes
    toc_depth: 3
    toc_float: TRUE

---

# Instructor

      Sarah Dimakis, M.S.
      e-mail: sdimakis@uoregon.edu
      office hours: TBD
      location: Straub 461

# Course description

Moral psychology is the scientific study of how humans distinguish right from wrong and act (or fail to act) accordingly. Individuals develop variable and sometimes even opposing intuitions about how themselves and others should and should never behave. Some moral intuitions are universal (e.g., protecting the innocent), while others are cultural (e.g., sexual practices). How and why did humans develop these intuitions that many other animal species do not have? How do children learn to distinguish right from wrong? How do adult humans judge a behavior as morally right or wrong, and how and why do they often disagree? How do humans behave in immoral ways with a clear conscience? What is the relationship between religion and morality, and do religious people behave more morally than atheists? What are the implications of moral disagreements on our political and judicial systems? Can we resolve moral disagreements, or are our moral intuitions set in stone? We will explore these questions and more in this course.

This course is meant to be an introduction into moral psychology and therefore assignments do not presume prior knowledge. Prior experience reading psychology research is highly recommended. 

# Learning objectives 
In this course, you will be developing important skills that are transferable outside of the classroom, like introspection, critical thinking, writing, and speaking. You will be developing skills in consuming and evaluating psychology research, collaborating with peers, and communicating scientific research. Additionally, on completion of this course, you will be able to describe and identify important theories and research findings in moral psychology, read novel research in moral psychology from academic journals, and apply moral psychology theory and research findings to novel situations. 

# Estimated student workload
When you complete this course, you will earn 4 credits toward your degree. Four credits is equivalent to 120 hours of work across the term, or 12 hours per week for 10 weeks. You will spend 3 hours in class per week, and the remaining 90 hours will be split evenly between readings, homework assignments, and studying for and taking quizzes and exams.

# Required readings
There is no assigned textbook for this course. All readings will be posted on Canvas at the beginning of the course. Readings should be completed before the class date indicated on the schedule. 

# Grading
Your course grade will be determined by the following assignments:


| Assignment  |   Points   | 
|:-------------|:----------|
| Midterm exam  | 100 points |
| Final paper   | 100 points |
| Quizzes (25 points x4)  | 100 points |
| Homework (20 points x4) | 80 points  |
| Participation | 20 points  |
|     | = 400 points| 



## Midterm
There is one exam for this course, a midterm exam, which is scheduled on the first day of the fifth week of the course. The exam will consist of 5 matching, 5 fill-in-the-blank, 20 multiple choice, and 4 short answer questions. You can bring one 8x10 piece of paper of notes to the exam. 

## Final paper

Your final research paper will be due during finals week. The recommended page count is 4-5 pages double spaced. You will choose a research question from a list of topics, read relevant research on the topic, and discuss how the research findings answer or fail to answer the research question. Detailed instructions and a topic list will be given out after the midterm exam in week 5. 

## Quizzes

Every other week, as indicated on the syllabus, there will be a quiz on Canvas due at 11:59pm on Sunday. The quiz will test comprehension for reading and lecture material for the two weeks prior to the quiz. You may use readings, notes, the internet, etc., to succeed on the quiz (but you cannot use another person). The quizzes will be timed (25 minutes) and consist of 10 multiple choice questions and 5 matching questions. 


## Homework 
Every other week, as indicated on the syllabus, you will have structured homework assignments due on Canvas at 11:59pm on Sunday. The assignments are designed to help you work through the lecture and reading material with concrete, personally relevant examples, and provide an opportunity to think in depth about a topic before class group discussion.

## Participation

Showing up to class, turning in your assignments on time, and actively participating in group and class discussion is incredibly important to succeed in this course, so participation has been given a part of your grade to reflect its importance. Please let me know (via e-mail so that I have a record of it) if you need to miss a class. 

## Grades

The following grid provides the letter grade associated with each percent:


| | | | |
|:---------|:------------|:----------|:-----------|
| A 93-100% |   B 83-86.99%   | C 73-76.99% | D 63-66.99% |
| A- 90-92.99% | B- 80-82.99% | C- 70-72.99% | D- 60-62.99% |
| B+ 87-89.99% | C+ 77-79.99% | D+ 67-69.99% | F 59.99% or below |

**Note**: Grade cutoffs are set so that there is no “rounding up,” although I reserve the right to round up students who are very close to a grade interval and whose participation in class discussions was exemplary. I may assign an “A+” if a student demonstrates outstanding understanding of the material (on assignments and in class discussions).  

# Policies

## Late assignment policy
Please reach out to me in advance to a deadline if you need an extension on an assignment, including a timeframe of when you think you can finish the assignment by. I will not ask for a reason or a doctor’s note. My standard late penalty is 10% off of the assignment per day, but I will have a conversation with you before that is enforced so that you are not penalized for getting sick or having other out of the ordinary circumstances happen to you.


## Special Accommodations

The University of Oregon works to create inclusive learning environments. If there are aspects of the instruction or design of this course that result in disability-related barriers to your participation, please notify me as soon as possible. If you have a documented disability, please request that a counselor at the Accessible Education Center (uoaec@uoregon.edu, 541-346-1155) send a letter verifying the type of accommodation that is appropriate. For a list of resources provided by the Accessible Education Center, please see http://aec.uoregon.edu.

## Cheating/plagiarism
Any form of academic dishonesty, including getting outside help on assessments and plagiarizing of any kind are not productive to your learning and therefore will not be tolerated in this class. I will follow the procedure to handle misconduct as outlined by the University. This means that instances of suspected cheating or plagiarizing will be reported to the University, and at the very least, you will receive a zero on the assignment. Please familiarize yourself with the University of Oregon’s conduct code, found at http://conduct.uoregon.edu. You are responsible for behaving in accordance with this policy and continued enrollment in this class will be considered implicit agreement that you have read and accepted the terms of that policy. If you have questions about what is considered academic dishonesty for this course, please reach out and ask.

## Email policy
If you email me, I will get back to you within 24 hours, or 48 hours at the latest. If I do not respond to your email within 24 hours, please resend it because I may have not received it. I recommend attending my office hours (or making an appointment with me) if you have multiple questions, or you would like to brainstorm with me about an assignment, or you would like to go over a past quiz/exam.

## Diversity and classroom climate

While studying moral psychology, we are bound to hear from others who do not agree with our moral values. I do not expect to agree with you on everything, and I do not expect you to agree with your classmates on everything. We are a group with diverse backgrounds and experiences. We must therefore make it a priority that everyone in this class (students and instructor) have the opportunity to offer opinions, hear one another’s opinions, and make arguments and challenge ideas. This is only possible when we respect each other. Here are a few ground rules that I propose that we follow, and I am open to discussing more:

1. Criticize ideas and not people.  Instead of “you are wrong and dumb for thinking that,” you want to say “let’s talk about that – I don’t think that theory is supported by the research.”

2. Avoid making assumptions about others. Without complete information about other people, we try to fill in the missing information but fall short. When we sit back and listen, we learn things we could not expect.

3. Allow others to make mistakes and learn from them. Learn from each other’s mistakes. We don’t always say what we mean, and we are all learning and growing in this class.

4. Keep an open mind - don’t assume your beliefs are fully formed and that you can’t learn from others.

5. Treat others with respect, even when you disagree. Always treat others how you would like to be treated.

That being said, if you do not feel comfortable participating in a class discussion or believe there is more I could be doing to promote a more effective learning environment, I urge you to come talk to me. I will always listen to your concerns with respect and an open mind and will make adjustments when appropriate.

