---
title: ""
output: 
  html_document: 
    toc: yes
    toc_depth: 1
    toc_float: yes
    css: table.css
---

```{css, echo = FALSE}

.fa-apple {
    color: #A3AAAE;
}

.fa-apple:hover {
    color: #dfe1e2;
}

.fa-spotify {
    color: #1DB954;
}

.fa-spotify:hover {
    color: #a2f1be;
}

.fa-google {
    color: #F4B400;
}

.fa-google:hover {
    color: #ffe294;
}

.fa-video {
    color: #61a0ff;
}

.fa-video:hover {
    color: #e6f0ff;
}

.fa-globe {
    color: #61a0ff;
}


.fa-globe:hover {
    color: #e6f0ff;
}


```

# Recommended books

Books about moral psychology and moral philosophy, mostly for a general audience.

- **The (Honest) Truth About Dishonesty: How We Lie to Everyone - Especially Ourselves** *Dan Ariely* [<i class="fas fa-globe"></i>](https://www.goodreads.com/book/show/13426114-the-honest-truth-about-dishonesty)

- **Just Babies: The Origins of Good and Evil** *Paul Bloom* [<i class="fas fa-globe"></i>](https://www.goodreads.com/book/show/17380034-just-babies)

- **Against Empathy: The Case for Rational Compassion** *Paul Bloom*  [<i class="fas fa-globe"></i>](https://www.goodreads.com/book/show/29100194-against-empathy)

- **Telling Lies: Clues to Deceit in the Marketplace, Politics, and Marriage** *Paul Ekman* [<i class="fas fa-globe"></i>](https://www.goodreads.com/book/show/252429.Telling_Lies)

- **Moral Tribes: Emotion, Reason, and the Gap Between Us and Them** *Joshua Greene* [<i class="fas fa-globe"></i>](https://www.goodreads.com/book/show/17707599-moral-tribes)

- **The Righteous Mind: Why Good People Are Divided by Politics and Religion** *Jonathon Haidt* [<i class="fas fa-globe"></i>](https://www.goodreads.com/book/show/11324722-the-righteous-mind)

- **The Happiness Hypothesis: Finding Modern Truth in Ancient Wisdom** *Jonathon Haidt*  [<i class="fas fa-globe"></i>](https://www.goodreads.com/book/show/96884.The_Happiness_Hypothesis)

- **Moral minds: How Nature Designed Our Universal Sense of Right and Wrong** *Marc Hauser* [<i class="fas fa-globe"></i>](https://www.goodreads.com/book/show/135663.Moral_Minds)

- **Moral Politics: How Liberals and Conservatives Think** *George Lakoff* [<i class="fas fa-globe"></i>](https://www.goodreads.com/book/show/19134.Moral_Politics)

- **Justice: What's the right thing to do?** *Michael Sandel* [<i class="fas fa-globe"></i>](https://www.goodreads.com/book/show/6452731-justice)

- **Primates and Philosophers: How Morality Evolved** *Frans de Waal* [<i class="fas fa-globe"></i>](https://www.goodreads.com/book/show/192412.Primates_and_Philosophers)

- **The moral animal: Why We Are the Way We Are - The New Science of Evolutionary Psychology** *Robert Wright* [<i class="fas fa-globe"></i>](https://www.goodreads.com/book/show/681941.The_Moral_Animal)

- **The Lucifer Effect: Understanding How Good People Turn Evil** *Philip Zimbardo* [<i class="fas fa-globe"></i>](https://www.goodreads.com/book/show/359194.The_Lucifer_Effect)

- **What It Means to Be Moral: Why Religion Is Not Necessary for Living an Ethical Life** *Phil Zuckerman* [<i class="fas fa-globe"></i>](https://www.goodreads.com/book/show/44643009-what-it-means-to-be-moral)


# Recommended talks
TED talks about moral psychology and moral philosophy.

- **Our buggy moral code** *Dan Ariely* [<i class="fa fa-video"></i>](https://www.ted.com/talks/dan_ariely_our_buggy_moral_code?language=en)

- **Moral behavior in animals** *Frans de waal* [<i class="fa fa-video"></i>](https://www.ted.com/talks/frans_de_waal_moral_behavior_in_animals?language=en)

- **The moral roots of liberals and conservatives** *Jonathan Haidt* [<i class="fa fa-video"></i>](https://www.ted.com/talks/jonathan_haidt_the_moral_roots_of_liberals_and_conservatives)

- **Science can answer moral questions** *Sam Harris* [<i class="fa fa-video"></i>](https://www.ted.com/talks/sam_harris_science_can_answer_moral_questions)

- **Progress is not a zero sum game** *Robert Wright* [<i class="fa fa-video"></i>](https://www.ted.com/talks/robert_wright_progress_is_not_a_zero_sum_game)

- **The surprising decline in violence** *Steven Pinker* [<i class="fa fa-video"></i>](https://www.ted.com/talks/steven_pinker_the_surprising_decline_in_violence?language=en)

- **The strange politics of disgust** *David Pizarro* [<i class="fa fa-video"></i>](https://www.ted.com/talks/david_pizarro_the_strange_politics_of_disgust?language=en)

# Recommended podcasts
Podcasts from moral psychologists, moral philosophers, or psychologists that frequently discuss moral issues. These podcasts range from very academic to very causal. 

- **The Moral Science Podcast** *Amber Cazzell* [<i class="fab fa-apple"></i>](https://podcasts.apple.com/us/podcast/the-moral-science-podcast/id1468695145) [<i class="fab fa-spotify"></i>](https://open.spotify.com/show/0GaXHC2UcuErWfKlMl3dcf) [<i class="fab fa-google"></i>](https://podcasts.google.com/feed/aHR0cHM6Ly9hbmNob3IuZm0vcy9iZGRjYmM4L3BvZGNhc3QvcnNz?hl=en)

- **Making Sense** *Sam Harris* [<i class="fab fa-apple"></i>](https://podcasts.apple.com/us/podcast/making-sense-with-sam-harris/id733163012) [<i class="fab fa-spotify"></i>](https://open.spotify.com/show/5rgumWEx4FsqIY8e1wJNAk) [<i class="fab fa-google"></i>](https://podcasts.google.com/feed/aHR0cDovL3dha2luZ3VwLmxpYnN5bi5jb20vcnNz/episode/NGZmZGJiNGZjYWJkNGYzMDlmMDQ0ZjM4Y2MwZGJjN2E)

- **The Psychology Podcast** *Scott Barry Kaufman* [<i class="fab fa-apple"></i>](https://podcasts.apple.com/us/podcast/the-psychology-podcast-with-scott-barry-kaufman/id942777522) [<i class="fab fa-spotify"></i>](https://open.spotify.com/show/4POIiQQjnQOuz0AqnLk3KZ) [<i class="fab fa-google"></i>](https://podcasts.google.com/feed/aHR0cHM6Ly9hbmNob3IuZm0vcy8yZjU1YmZjMC9wb2RjYXN0L3Jzcw==)

- **Very Bad Wizards** *David Pizarro & Tamler Sommers* [<i class="fab fa-apple"></i>](https://podcasts.apple.com/us/podcast/very-bad-wizards/id557975157) [<i class="fab fa-spotify"></i>](https://open.spotify.com/show/4gGFerFYkDHnezTlwExEbu?si=AU5C1BzDTMCaS7uc_wqrjw) [<i class="fab fa-google"></i>](https://play.google.com/music/managemusic?t=Very_Bad_Wizards)

- **Two Psychologists Four beers** *Yoel Inbar & Michael Inzlicht* [<i class="fab fa-apple"></i>](https://podcasts.apple.com/us/podcast/two-psychologists-four-beers/id1387529624) [<i class="fab fa-spotify"></i>](https://open.spotify.com/show/2C9rFEeoHdUp2mXtXKlEnd) [<i class="fab fa-google"></i>](https://podcasts.google.com/feed/aHR0cHM6Ly93d3cuZm91cmJlZXJzLmNvbS9yc3M)

- **No Stupid Questions** *Stephen Dubner & Angela Duckworth* [<i class="fab fa-apple"></i>](https://podcasts.apple.com/us/podcast/no-stupid-questions/id1510056899) [<i class="fab fa-spotify"></i>](https://open.spotify.com/show/6Z49m4VQ4TfQ28Cnl42yiT) [<i class="fab fa-google"></i>](https://podcasts.google.com/feed/aHR0cHM6Ly93d3cub21ueWNvbnRlbnQuY29tL2QvcGxheWxpc3QvYWFlYTRlNjktYWY1MS00OTVlLWFmYzktYTk3NjAxNDY5MjJiL2RjNWI1NWNhLTVmMDAtNDA2My1iNDdmLWFiODcwMTYzZDJiNy9jYTYzYWE1Mi1lZjdiLTQzZWUtOGJhNS1hYjg3MDE2NDUyMzEvcG9kY2FzdC5yc3M)