---
title: "<b>Homework 4</b>"
output:
  html_document:
    theme: cosmo
    css: table.css
---

***Instructions***: For this homework assignment, you will submit a rough draft of your term paper. Your rough draft doesn't need to be the full length of your final draft, or pass all of the grading criteria. However, you will be able to get better feedback on your draft if it is complete. You will receive feedback from both the instructor and a peer on this draft. You can access the full grading criteria for the term paper <u>[here](extra/final.html).</u> Please submit your draft to Canvas by Sunday at 11:59pm. I recommend this structure:

## Introduction (2-3 paragraphs)

In this first section, you should introduce your research question. What is your question and why is it important? At the end of this section, you want to give a one sentence summary "answer" to your question, which will be the thesis of your paper. An excellent thesis is usually one that is nuanced, i.e., it gives not just a yes or no answer, but describes some limit or constraint. 

## Body (2+ pages)

In this section, you should provide evidence for your thesis. How did you determine the "answer" to your question? In this space, describe relevant studies and how they help answer your question.

## Conclusion (1-3 paragraphs)

In the final section, you should restate your findings and then describe what there is still left to know about the topic. Give recommendations for future research on this topic. What are the limitations to current research on this topic? How would *you* design a study to answer this question?
