---
title: "<b>Homework 5</b>"
output:
  html_document:
    theme: cosmo
    css: table.css
---


***Instructions***: An important part of research is getting and giving feedback. For this assignment, you will read a classmate's paper and give them <u>constructive</u> feedback. You can access the grading criteria <u>[here](extra/final.html).</u> Please keep your tone as helpful and kind as possible - we are all learning to be better writers! The peer review consists of two parts (make sure to submit both parts to Canvas by Sunday at 11:59pm for full credit):

1. Leave comments on the text (preferably with word track changes)

    - Correct any spelling, grammatical, or otherwise syntax errors you see. You shouldn't be rewriting any sentences, but you should fix any "small" errors that you see (e.g., writing desert when they mean dessert).
    
    - Flag any sentences that are unclear, wordy, or otherwise confusing.
    
    - Leave suggestions of what could be added or taken away, or if something could be organized differently.
  
2. Summarize your review

    - 1-3 things that you liked about the paper
    
    - 1-3 areas of improvement (including any components from the rubric that are missing)