---
title: "Moral emotions pt 1"
subtitle: "Week 8 - Moral Psychology"
output:
  xaringan::moon_reader:
    css: [default, custom_fonts.css, custom_theme.css, custom.css]
---

# Week 8

This week, we will be discussing moral emotions 

.highlight-gray[In week 8:]

- What makes an emotion moral? 

---

# Moral emotions

<center>

<iframe width="560" height="315" src="https://www.youtube.com/embed/AcpxW8DGagE" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

https://www.youtube.com/watch?v=AcpxW8DGagE

---

# Moral emotions

Moral emotions
• Moral emotions: social emotions that affect moral behavior
• They are responses to moral violations: “this is wrong with no exception”
• Or they can motivate moral behavior: to “do the right thing”

---

• Self-conscious emotions – felt when we violate a moral/ social norm
• embarrassment – felt when one violates a social convention, motivates to hide
• shame – felt after violating a moral norm, “I am a bad person,” motivates to hide (darker)
• guilt – when one feels they caused harm, loss, distress to another, motivates apology/
confession

---

Other-condemning emotions – felt when others violate a moral/social norm
• anger – response to unjustified insult and injustice, motivates to attack/ get revenge
• disgust – feeling that something is revolting, motivates to avoid then purify self
• contempt – looking down on someone, feeling morally superior, motivates distance

---

Other-praising – felt when others do something moral/ positive
• gratitude – feeling of being grateful for the good deed of another, motivates prosocial
behavior
• awe – amazement or sometimes fright to something unexpected, motivates admiration
• elevation – warmth and expansive feeling from seeing a good deed, motivates bettering
oneself

---
• Other-suffering – felt when someone else is suffering
• compassion - being moved by another’s suffering, motivates help, comfort, to alleviate pain